### ISSUE TITLE
How to handle the digits of suffix in image name?

### ISSUE THREAD

**Issue by balaji101010** [aliyigitbireroglu/flutter-image-sequence-animator#1]
```
ImageSequenceAnimator(
                    "assets/img/fraisier/AnimatedImage1", //folderName
                    "R19I1-", //fileName
                    1, //suffixStart
                    13, //suffixCount
                    "jpg", //fileFormat
                    60, //frameCount
                    isAutoPlay: true,
                  )
```

My Images names look like this,

images/R19I1-01.jpg
images/R19I1-02.jpg

**Unable to load asset: assets/img/fraisier/AnimatedImage1/R19I1-0000000000001.jpg**
I am facing this issue! 
Can you please tell me how to handle the digits of the name? Or is there any fix?

**Comment by aliyigitbireroglu** [comment]
Set the suffixCount to 2. The minimum number of digits for your suffix format is 2: "01", "02", etc.
