### ISSUE TITLE
Using image sequence animator with Image.network

### ISSUE THREAD

**Issue by roderikpeeters** [aliyigitbireroglu/flutter-image-sequence-animator#2]
I really love this plugin, Im using it to create a "stop motion" from the lasted saved webcam screens. However these screens are all stored online and ofcourse updated every X minute.

I would really love to use this plugin, where I can give a set of network images, instead of giving a location for my image assets.

**Comment by aliyigitbireroglu** [comment]
Hello,

Sorry for the late response. The trick of the package is to load a sequence of images as fast as possible so that they seem like a video/GIF file. I am not sure if this can be achieved as seamlessly with network images.

**Comment by roderikpeeters** [comment]
No problem! 

So for a good solution for this, it should have a preload. Only after fetching all the images the animator can start.

**Comment by aliyigitbireroglu** [comment]
I also thought about that but depending on the size and quantity of the images, that can be a very memory demanding operation.

**Comment by roderikpeeters** [comment]
True! But for my images they are only 20kb per image, I would use 20 images.

**Comment by roderikpeeters** [comment]
yeah I can, I can give a json file with images or just some links?

**Comment by aliyigitbireroglu** [comment]
A list of links would be enough for now.

**Comment by aliyigitbireroglu** [comment]
No nudies pls.

**Comment by roderikpeeters** [comment]
https://www.noorderlichtapp.nl/aurora_1.jpg
https://www.noorderlichtapp.nl/aurora_2.jpg
https://www.noorderlichtapp.nl/aurora_3.jpg
https://www.noorderlichtapp.nl/aurora_4.jpg
https://www.noorderlichtapp.nl/aurora_5.jpg
https://www.noorderlichtapp.nl/aurora_6.jpg
https://www.noorderlichtapp.nl/aurora_7.jpg
https://www.noorderlichtapp.nl/aurora_8.jpg
https://www.noorderlichtapp.nl/aurora_9.jpg
https://www.noorderlichtapp.nl/aurora_10.jpg

**Comment by aliyigitbireroglu** [comment]
Hello! 

Finally, I've had some time to continue my personal works and I was able to do an optimised online version of this library. It is uploaded both on pub.dev and here. Take a look and let me know what you think. If you need any help, feel free to ask.
