### ISSUE TITLE
Why is Color white chosen as default?

### ISSUE THREAD

**Issue by Zeynal7** [aliyigitbireroglu/flutter-image-sequence-animator#4]
I have been struggling to find the reason why my sequence is not playing and nothing is shown. Later I realized that my background is white, and default color is also white, so I was not seeing anything. The default should just be null. Is there any reason that white is chosen?

**Comment by aliyigitbireroglu** [comment]
You are right. I coded this library when I was still mostly learning Flutter. I will change that and upload a new version to avoid future confusion. Thank you very much.
